name: orphans
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - matplotlib
  - numpy
  - scipy
  - astropy
  - pandas
  - pyarrow
  - jupyter
  - sphinx
  - sphinx_rtd_theme
  - seaborn
  - dustmaps
  - markupsafe==2.0.1