name: orphans
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - matplotlib
  - numpy
  - scipy
  - astropy
  - pandas
  - pyarrow
  - jupyterlab
  - seaborn
  - dustmaps
  - emcee
  - getdist
  - sphinx
  - sphinx_rtd_theme
  - pytest-cov
  - pylint
  - markupsafe==2.0.1
  - jetsimpy